### ISSUE TITLE
Post: Spot sharing

### ISSUE THREAD

**Issue by davatron5000** [Paravel/DayTrip-Blog#1]

**Comment by TrentWalton** [comment]
Got a post in _drafts. I figure we publish when we hit <a href="https://github.com/Paravel/DayTrip/issues/154">DayTrip Issue 154</a>. It wasn’t imperative, but figured it’d be fine to wait.

Will update the screenshot 

<img width="500" alt="screen shot 2015-11-12 at 2 26 57 pm" src="https://cloud.githubusercontent.com/assets/271248/11130228/83fd40f2-8949-11e5-9bed-da22d39c4465.png">
